/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bakalarka;

import java.awt.Color;
import java.awt.Cursor;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.awt.event.MouseMotionListener;
import java.io.File;
import java.io.IOException;
import java.text.DecimalFormat;
import java.util.List;
import javafx.util.Pair;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JScrollPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.JTableHeader;
import javax.swing.table.TableColumn;
import javax.swing.table.TableColumnModel;

/**
 *
 * @author Anry
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
        //setSize(1084, 750);
        //MainPanel.setSize(1084,750);
        //BoundsPanel.setSize(1072,725);
        //MainPanel.setBounds(0, 0, WIDTH, HEIGHT);
        //BoundsPanel.setBounds(0, 0, WIDTH, HEIGHT);
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width / 2 - this.getSize().width / 2, dim.height / 2 - this.getSize().height / 2);
        MainPanel.setVisible(false);
        MainPanel.setBackground(Color.BLACK);
        HeadPanel.setBackground(Color.WHITE);
        add(MainPanel);
        MainPanel.setVisible(true);
        eventHandler = new EventHandler();
        handlerMouse = new HandleMouseEvt();
        jButton1.addActionListener(eventHandler);
        jButton1.setIcon(new ImageIcon(getClass().getResource("Click1_def.png")));
        jButton1.addMouseListener(handlerMouse);
        jButton1.addMouseMotionListener(handlerMouse);
        jButton2.setIcon(new ImageIcon(getClass().getResource("Click2_def.png")));
        jButton2.addMouseListener(handlerMouse);
        jButton2.addMouseMotionListener(handlerMouse);
        jButton2.addActionListener(eventHandler);
        jScrollPane2.setBorder(null);
        jScrollPane3.setBorder(null);
        jScrollPane4.setBorder(null);
        jScrollPane5.setBorder(null);
        jScrollPane6.setBorder(null);
        jScrollPane7.setBorder(null);
        jButton3.setIcon(new ImageIcon(getClass().getResource("Click3_def.png")));
        jButton3.addMouseListener(handlerMouse);
        jButton3.addMouseMotionListener(handlerMouse);
        jButton5.setIcon(new ImageIcon(getClass().getResource("Click4_def.png")));
        jButton5.addMouseListener(handlerMouse);
        jButton5.addMouseMotionListener(handlerMouse);
        jButton6.setIcon(new ImageIcon(getClass().getResource("RunBut1.png")));
        jButton6.addMouseListener(handlerMouse);
        jButton6.addMouseMotionListener(handlerMouse);
        jScrollPane7.setVerticalScrollBarPolicy(JScrollPane.VERTICAL_SCROLLBAR_ALWAYS);
        jScrollPane7.setHorizontalScrollBarPolicy(JScrollPane.HORIZONTAL_SCROLLBAR_AS_NEEDED);
        checker3.setVisible(false);
        jPanel1.setSize(WIDTH, 519);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        MainPanel = new java.awt.Panel();
        BoundsPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        OrdersPane = new javax.swing.JTextPane();
        OLabel1 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        OrdersPane1 = new javax.swing.JTextPane();
        jScrollPane5 = new javax.swing.JScrollPane();
        OrdersPane2 = new javax.swing.JTextPane();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        OrdersPane3 = new javax.swing.JTextPane();
        HeadPanel = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        ContactTxt = new javax.swing.JTextPane();
        panel1 = new java.awt.Panel();
        logoLab = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        topPanel = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        exitLabel = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        exitLabel1 = new javax.swing.JLabel();
        verticalLinePanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        horizontalLinePanel = new javax.swing.JPanel();
        horizontalLinePanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        misstakesArea = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        infoCheckNumField = new javax.swing.JTextField();
        missNumCheckField = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        checker1 = new javax.swing.JLabel();
        checker2 = new javax.swing.JLabel();
        horizontalLinePanel2 = new javax.swing.JPanel();
        infoOperationNumField = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        checker3 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MMCITÉ - Sokolík");
        setBackground(new java.awt.Color(250, 250, 250));
        setBounds(new java.awt.Rectangle(100, 100, 100, 100));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setUndecorated(true);

        MainPanel.setBackground(new java.awt.Color(0, 0, 0));

        BoundsPanel.setBackground(new java.awt.Color(255, 255, 255));
        BoundsPanel.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 1, 0, 1, new java.awt.Color(0, 0, 0)));

        jTable1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Celkový obrat", null},
                {"Obrat za PlayCité", null},
                {"Obrat za Mestský Mobiliár", null}
            },
            new String [] {
                "", "Skutočný obrat"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setGridColor(new java.awt.Color(70, 70, 70));
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setResizable(false);
            jTable1.getColumnModel().getColumn(1).setMinWidth(130);
            jTable1.getColumnModel().getColumn(1).setMaxWidth(230);
        }
        jTable1.getAccessibleContext().setAccessibleParent(this);

        OrdersPane.setEditable(false);
        OrdersPane.setBackground(new java.awt.Color(240, 240, 240));
        OrdersPane.setBorder(null);
        OrdersPane.setContentType("text/html"); // NOI18N
        OrdersPane.setFont(new java.awt.Font("Traditional Arabic", 0, 16)); // NOI18N
        OrdersPane.setText("<html>\rTento program pracuje so súbormi typu Excel ver. 12 a nižšej.</html>\r ");
        OrdersPane.setRequestFocusEnabled(false);
        OrdersPane.setSelectionColor(new java.awt.Color(255, 255, 255));
        jScrollPane3.setViewportView(OrdersPane);

        OLabel1.setFont(new java.awt.Font("Traditional Arabic", 1, 14)); // NOI18N
        OLabel1.setText("Pokyny k spracovaniu:");

        OrdersPane1.setEditable(false);
        OrdersPane1.setBackground(new java.awt.Color(240, 240, 240));
        OrdersPane1.setBorder(null);
        OrdersPane1.setContentType("text/html"); // NOI18N
        OrdersPane1.setFont(new java.awt.Font("Traditional Arabic", 0, 15)); // NOI18N
        OrdersPane1.setText("<html>\rProgram vezme dokument \"Náklady a Výnosy\" preverí jeho správnosť a nakoniec ho porovná s \"Obchodným plánom porniku\"</html>\r ");
        OrdersPane1.setRequestFocusEnabled(false);
        OrdersPane1.setSelectionColor(new java.awt.Color(255, 255, 255));
        jScrollPane4.setViewportView(OrdersPane1);

        OrdersPane2.setEditable(false);
        OrdersPane2.setBackground(new java.awt.Color(240, 240, 240));
        OrdersPane2.setBorder(null);
        OrdersPane2.setContentType("text/html"); // NOI18N
        OrdersPane2.setFont(new java.awt.Font("Traditional Arabic", 0, 16)); // NOI18N
        OrdersPane2.setText("<html>\rPri nájdení potencionálnej chyby pri generovaní dokumentov automatickým procesom navrhne opravu chybných údajov.</html>\r ");
        OrdersPane2.setRequestFocusEnabled(false);
        OrdersPane2.setSelectionColor(new java.awt.Color(255, 255, 255));
        jScrollPane5.setViewportView(OrdersPane2);

        jPanel2.setBackground(new java.awt.Color(255, 125, 0));

        OrdersPane3.setEditable(false);
        OrdersPane3.setBackground(new java.awt.Color(255, 125, 0));
        OrdersPane3.setBorder(null);
        OrdersPane3.setContentType("text/html"); // NOI18N
        OrdersPane3.setFont(new java.awt.Font("Traditional Arabic", 0, 15)); // NOI18N
        OrdersPane3.setText("<html>Výstupom programu je:<br>Dohladanie a zobrazenie potencionálnych chýb<br>Doplnenie požadovaných údajov  do obchodného plánu podniku<br> Informácie o počtu operácií,  preverených údajoch a počte  možných netrovnalostí<br> Možnosť spracovania finančnej  analýzy podniku</html>");
        OrdersPane3.setToolTipText("");
        OrdersPane3.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        OrdersPane3.setRequestFocusEnabled(false);
        OrdersPane3.setSelectionColor(new java.awt.Color(255, 255, 255));
        jScrollPane6.setViewportView(OrdersPane3);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 247, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 193, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 257, Short.MAX_VALUE)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(OLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(13, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(OLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        ContactTxt.setEditable(false);
        ContactTxt.setBorder(null);
        ContactTxt.setFont(new java.awt.Font("Traditional Arabic", 1, 14)); // NOI18N
        ContactTxt.setText("Kontakt na autora               Bc. Andrej SOKOLÍK sokolikandrej@gmail.com Bakalárska práca");
        ContactTxt.setRequestFocusEnabled(false);
        ContactTxt.setSelectionColor(new java.awt.Color(255, 255, 255));
        jScrollPane2.setViewportView(ContactTxt);
        ContactTxt.getAccessibleContext().setAccessibleParent(HeadPanel);

        panel1.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 16, Short.MAX_VALUE)
        );

        logoLab.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bakalarka/img_files/cabCompanyLogo_960.jpg"))); // NOI18N

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bakalarka/img/tittle.png"))); // NOI18N

        javax.swing.GroupLayout HeadPanelLayout = new javax.swing.GroupLayout(HeadPanel);
        HeadPanel.setLayout(HeadPanelLayout);
        HeadPanelLayout.setHorizontalGroup(
            HeadPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HeadPanelLayout.createSequentialGroup()
                .addComponent(logoLab)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 454, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(73, 73, 73)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
            .addComponent(panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        HeadPanelLayout.setVerticalGroup(
            HeadPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HeadPanelLayout.createSequentialGroup()
                .addGroup(HeadPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(logoLab)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );

        topPanel.setBackground(new java.awt.Color(17, 17, 17));
        topPanel.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                topPanelMouseDragged(evt);
            }
        });
        topPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                topPanelMousePressed(evt);
            }
        });

        jPanel4.setBackground(new java.awt.Color(255, 125, 0));
        jPanel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel4MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel4MouseExited(evt);
            }
        });

        exitLabel.setFont(new java.awt.Font("Traditional Arabic", 1, 24)); // NOI18N
        exitLabel.setForeground(new java.awt.Color(255, 255, 255));
        exitLabel.setText("-");
        exitLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                exitLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                exitLabelMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(exitLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(exitLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 7, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel3.setBackground(new java.awt.Color(255, 125, 0));
        jPanel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel3MouseExited(evt);
            }
        });

        exitLabel1.setFont(new java.awt.Font("Traditional Arabic", 1, 24)); // NOI18N
        exitLabel1.setForeground(new java.awt.Color(255, 255, 255));
        exitLabel1.setText("X");
        exitLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitLabel1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                exitLabel1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                exitLabel1MouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(exitLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(exitLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout topPanelLayout = new javax.swing.GroupLayout(topPanel);
        topPanel.setLayout(topPanelLayout);
        topPanelLayout.setHorizontalGroup(
            topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, topPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );
        topPanelLayout.setVerticalGroup(
            topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        verticalLinePanel.setBackground(new java.awt.Color(0, 0, 0));
        verticalLinePanel.setPreferredSize(new java.awt.Dimension(2, 0));

        javax.swing.GroupLayout verticalLinePanelLayout = new javax.swing.GroupLayout(verticalLinePanel);
        verticalLinePanel.setLayout(verticalLinePanelLayout);
        verticalLinePanelLayout.setHorizontalGroup(
            verticalLinePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2, Short.MAX_VALUE)
        );
        verticalLinePanelLayout.setVerticalGroup(
            verticalLinePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 504, Short.MAX_VALUE)
        );

        jLabel1.setFont(new java.awt.Font("Traditional Arabic", 0, 18)); // NOI18N
        jLabel1.setText("Krok 1.");
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        horizontalLinePanel.setBackground(new java.awt.Color(0, 0, 0));
        horizontalLinePanel.setPreferredSize(new java.awt.Dimension(195, 2));

        javax.swing.GroupLayout horizontalLinePanelLayout = new javax.swing.GroupLayout(horizontalLinePanel);
        horizontalLinePanel.setLayout(horizontalLinePanelLayout);
        horizontalLinePanelLayout.setHorizontalGroup(
            horizontalLinePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 312, Short.MAX_VALUE)
        );
        horizontalLinePanelLayout.setVerticalGroup(
            horizontalLinePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2, Short.MAX_VALUE)
        );

        horizontalLinePanel1.setBackground(new java.awt.Color(0, 0, 0));
        horizontalLinePanel1.setPreferredSize(new java.awt.Dimension(195, 2));

        javax.swing.GroupLayout horizontalLinePanel1Layout = new javax.swing.GroupLayout(horizontalLinePanel1);
        horizontalLinePanel1.setLayout(horizontalLinePanel1Layout);
        horizontalLinePanel1Layout.setHorizontalGroup(
            horizontalLinePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 308, Short.MAX_VALUE)
        );
        horizontalLinePanel1Layout.setVerticalGroup(
            horizontalLinePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jLabel2.setFont(new java.awt.Font("Traditional Arabic", 1, 18)); // NOI18N
        jLabel2.setText("<html><b>Prehlad potenciálnych chýb:</b></html>");
        jLabel2.setToolTipText("");

        jLabel3.setFont(new java.awt.Font("Traditional Arabic", 0, 18)); // NOI18N
        jLabel3.setText("Krok 2.");
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel4.setFont(new java.awt.Font("Traditional Arabic", 0, 18)); // NOI18N
        jLabel4.setText("Krok 3.");
        jLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        misstakesArea.setEditable(false);
        misstakesArea.setColumns(20);
        misstakesArea.setFont(new java.awt.Font("Monospaced", 1, 9)); // NOI18N
        misstakesArea.setRows(5);
        misstakesArea.setAutoscrolls(false);
        misstakesArea.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 0, 2, 0, new java.awt.Color(0, 0, 0)));
        misstakesArea.setMargin(new java.awt.Insets(0, 2, 0, 2));
        jScrollPane7.setViewportView(misstakesArea);

        jLabel6.setFont(new java.awt.Font("Traditional Arabic", 1, 14)); // NOI18N
        jLabel6.setText("Preverených údajov");

        jLabel7.setFont(new java.awt.Font("Traditional Arabic", 1, 14)); // NOI18N
        jLabel7.setText("Nájdených nezrovnalostí");

        infoCheckNumField.setBackground(new java.awt.Color(230, 230, 230));
        infoCheckNumField.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        infoCheckNumField.setForeground(new java.awt.Color(70, 70, 70));
        infoCheckNumField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        infoCheckNumField.setToolTipText("");
        infoCheckNumField.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 3, 3, 2, new java.awt.Color(70, 70, 70)));

        missNumCheckField.setBackground(new java.awt.Color(230, 230, 230));
        missNumCheckField.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        missNumCheckField.setForeground(new java.awt.Color(70, 70, 70));
        missNumCheckField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        missNumCheckField.setToolTipText("");
        missNumCheckField.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 3, 3, 2, new java.awt.Color(70, 70, 70)));

        jLabel8.setFont(new java.awt.Font("Traditional Arabic", 0, 18)); // NOI18N
        jLabel8.setText("Krok 4.");
        jLabel8.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        checker1.setBackground(new java.awt.Color(255, 255, 255));

        checker2.setBackground(new java.awt.Color(255, 255, 255));

        horizontalLinePanel2.setBackground(new java.awt.Color(0, 0, 0));
        horizontalLinePanel2.setPreferredSize(new java.awt.Dimension(195, 2));

        javax.swing.GroupLayout horizontalLinePanel2Layout = new javax.swing.GroupLayout(horizontalLinePanel2);
        horizontalLinePanel2.setLayout(horizontalLinePanel2Layout);
        horizontalLinePanel2Layout.setHorizontalGroup(
            horizontalLinePanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 312, Short.MAX_VALUE)
        );
        horizontalLinePanel2Layout.setVerticalGroup(
            horizontalLinePanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2, Short.MAX_VALUE)
        );

        infoOperationNumField.setBackground(new java.awt.Color(230, 230, 230));
        infoOperationNumField.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        infoOperationNumField.setForeground(new java.awt.Color(70, 70, 70));
        infoOperationNumField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        infoOperationNumField.setToolTipText("");
        infoOperationNumField.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 3, 3, 2, new java.awt.Color(70, 70, 70)));

        jLabel9.setFont(new java.awt.Font("Traditional Arabic", 1, 14)); // NOI18N
        jLabel9.setText("<html><b>Počet operácií</b></html>");

        checker3.setBackground(new java.awt.Color(255, 255, 255));
        checker3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bakalarka/ch.png"))); // NOI18N

        jButton5.setBackground(new java.awt.Color(255, 255, 255));
        jButton5.setToolTipText("");
        jButton5.setBorder(null);
        jButton5.setPreferredSize(new java.awt.Dimension(73, 43));

        jButton6.setBackground(new java.awt.Color(255, 255, 255));
        jButton6.setBorder(null);
        jButton6.setPreferredSize(new java.awt.Dimension(139, 55));

        jButton3.setBorder(null);
        jButton3.setPreferredSize(new java.awt.Dimension(198, 85));

        jButton1.setBorder(null);
        jButton1.setPreferredSize(new java.awt.Dimension(198, 99));

        jButton2.setBorder(null);
        jButton2.setPreferredSize(new java.awt.Dimension(198, 99));

        javax.swing.GroupLayout BoundsPanelLayout = new javax.swing.GroupLayout(BoundsPanel);
        BoundsPanel.setLayout(BoundsPanelLayout);
        BoundsPanelLayout.setHorizontalGroup(
            BoundsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(topPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(BoundsPanelLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(BoundsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(HeadPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(BoundsPanelLayout.createSequentialGroup()
                        .addGroup(BoundsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(horizontalLinePanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(verticalLinePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(BoundsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(BoundsPanelLayout.createSequentialGroup()
                                .addGroup(BoundsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(BoundsPanelLayout.createSequentialGroup()
                                        .addGroup(BoundsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(BoundsPanelLayout.createSequentialGroup()
                                                .addGap(32, 32, 32)
                                                .addGroup(BoundsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGroup(BoundsPanelLayout.createSequentialGroup()
                                                        .addGap(10, 10, 10)
                                                        .addGroup(BoundsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addComponent(checker2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addComponent(checker3, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addComponent(checker1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                                .addGap(18, 18, 18)
                                                .addGroup(BoundsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addGroup(BoundsPanelLayout.createSequentialGroup()
                                                .addGap(20, 20, 20)
                                                .addComponent(horizontalLinePanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(BoundsPanelLayout.createSequentialGroup()
                                                .addGap(28, 28, 28)
                                                .addGroup(BoundsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(27, 27, 27)
                                                .addGroup(BoundsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(infoCheckNumField, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(missNumCheckField, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                        .addGap(51, 51, 51)
                                        .addGroup(BoundsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(BoundsPanelLayout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(horizontalLinePanel, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(50, 50, 50))
                            .addGroup(BoundsPanelLayout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(72, 72, 72)
                                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(infoOperationNumField, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(8, 8, 8)))))
                .addContainerGap())
        );
        BoundsPanelLayout.setVerticalGroup(
            BoundsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BoundsPanelLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(HeadPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(396, 396, 396)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(BoundsPanelLayout.createSequentialGroup()
                .addComponent(topPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(137, 137, 137)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(BoundsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(BoundsPanelLayout.createSequentialGroup()
                        .addGroup(BoundsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(BoundsPanelLayout.createSequentialGroup()
                                .addGroup(BoundsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(BoundsPanelLayout.createSequentialGroup()
                                        .addGap(13, 13, 13)
                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(checker1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(51, 51, 51)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(checker2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(BoundsPanelLayout.createSequentialGroup()
                                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(BoundsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(BoundsPanelLayout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(BoundsPanelLayout.createSequentialGroup()
                                        .addGap(21, 21, 21)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(checker3, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addComponent(horizontalLinePanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(BoundsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel6)
                                    .addComponent(infoCheckNumField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(23, 23, 23)
                                .addGroup(BoundsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel7)
                                    .addComponent(missNumCheckField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(horizontalLinePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(BoundsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(BoundsPanelLayout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(BoundsPanelLayout.createSequentialGroup()
                                .addGroup(BoundsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(BoundsPanelLayout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(BoundsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(infoOperationNumField, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(BoundsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(BoundsPanelLayout.createSequentialGroup()
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(BoundsPanelLayout.createSequentialGroup()
                                            .addGap(22, 22, 22)
                                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(BoundsPanelLayout.createSequentialGroup()
                        .addGroup(BoundsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(verticalLinePanel, javax.swing.GroupLayout.DEFAULT_SIZE, 504, Short.MAX_VALUE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(horizontalLinePanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(57, 57, 57))))
        );

        javax.swing.GroupLayout MainPanelLayout = new javax.swing.GroupLayout(MainPanel);
        MainPanel.setLayout(MainPanelLayout);
        MainPanelLayout.setHorizontalGroup(
            MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BoundsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        MainPanelLayout.setVerticalGroup(
            MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainPanelLayout.createSequentialGroup()
                .addComponent(BoundsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 720, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 10, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jPanel3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MouseEntered
        jPanel3.setBackground(new Color(255, 165, 0));
        jPanel3.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_jPanel3MouseEntered

    private void jPanel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jPanel3MouseClicked

    private void jPanel3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MouseExited
        jPanel3.setBackground(new Color(255, 125, 0));
        jPanel3.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_jPanel3MouseExited

    private void exitLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitLabelMouseEntered
        exitLabel.setCursor(new Cursor(Cursor.HAND_CURSOR));
        jPanel4.setBackground(new Color(255, 165, 0));
    }//GEN-LAST:event_exitLabelMouseEntered

    private void jPanel4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel4MouseExited
        jPanel4.setBackground(new Color(255, 125, 0));
        jPanel4.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_jPanel4MouseExited

    private void jPanel4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel4MouseEntered
        jPanel4.setBackground(new Color(255, 165, 0));
        jPanel4.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_jPanel4MouseEntered

    private void jPanel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel4MouseClicked
        setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_jPanel4MouseClicked

    private void topPanelMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_topPanelMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();

        this.setLocation(x - mouseX, y - mouseY);
    }//GEN-LAST:event_topPanelMouseDragged

    private void topPanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_topPanelMousePressed
        mouseX = evt.getX();
        mouseY = evt.getY();
    }//GEN-LAST:event_topPanelMousePressed

    private void exitLabel1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitLabel1MouseEntered
        exitLabel1.setCursor(new Cursor(Cursor.HAND_CURSOR));
        jPanel3.setBackground(new Color(255, 165, 0));
    }//GEN-LAST:event_exitLabel1MouseEntered

    private void exitLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitLabel1MouseClicked
        System.exit(0);
    }//GEN-LAST:event_exitLabel1MouseClicked

    private void exitLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitLabelMouseClicked
        setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_exitLabelMouseClicked

    private void exitLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitLabelMouseExited
        jPanel4.setBackground(new Color(255, 125, 0));
    }//GEN-LAST:event_exitLabelMouseExited

    private void exitLabel1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitLabel1MouseExited
        jPanel3.setBackground(new Color(255, 125, 0));
    }//GEN-LAST:event_exitLabel1MouseExited

    /*public void fileChecker() {
        if (OrdersField.getText() != null) {
            f = new File(OrdersField.getText());
            if (f.isFile()) {
                checker1Bool = true;
                checkbox1.setEnabled(true);
                checkbox2.setEnabled(true);
                jButton5.setEnabled(true);
            } else {
                checker1Bool = false;
            }
            try {
                paint(Checker1, checker1Bool);
            } catch (IOException ex) {
                System.out.println("Checker1 have a little problem!");
            }
        }
        if (jTextField2.getText() != null) {
            planF = new File(jTextField2.getText());
            if (planF.isFile()) {
                checker2Bool = true;
                if (checker1Bool) {
                    checkbox3.setEnabled(true);
                    checkbox4.setEnabled(true);
                }
            } else {
                checker2Bool = false;
            }
            try {
                paint(Checker2, checker2Bool);
            } catch (IOException ex) {
                System.out.println("Checker2 have a little problem!");
            }
        }
        if (f.isFile()) {
            if (planF.isFile()) {
                try {
                    fp = new FileProcessor(f, planF);
                } catch (IOException ex) {
                    System.out.println("File processor with both files error!");
                }
            } else {
                try {
                    fp = new FileProcessor(f);
                } catch (IOException ex) {
                    System.out.println("File processor with one file error!");
                }
            }
        }
    }*/
    private class EventHandler implements ActionListener {

        @Override
        public void actionPerformed(ActionEvent e) {
            String userD = System.getProperty("user.home");
            System.out.println("Button Clicked!");
            chooser = new FileChooser();
            chooser.updateUI();
            chooser.setCurrentDirectory(new java.io.File(userD + "/Desktop"));
            chooser.setDialogTitle(chooserTitle);
            FileNameExtensionFilter filter = new FileNameExtensionFilter(
                    "Excel dokumenty", "xls", "xlsx");
            chooser.setFileFilter(filter);
            chooser.setFileSelectionMode(JFileChooser.FILES_ONLY);
            if (chooser.showOpenDialog(null) == JFileChooser.APPROVE_OPTION) {
                fileDir = "" + chooser.getCurrentDirectory();
                StringBuilder strB = new StringBuilder(fileDir);
                for (int i = 0; i < fileDir.length() - 1; i++) {
                    if (fileDir.charAt(i) == '\\') {
                        strB.setCharAt(i, '/');
                    }
                }
                if (fileDir.substring(fileDir.length() - 1, fileDir.length()).equals(".")) {
                    fileDir = fileDir.substring(0, fileDir.length() - 1);
                    sourceFolder = "" + strB + "" + chooser.getSelectedFile().getName();
                } else {
                    sourceFolder = "" + strB + "/" + chooser.getSelectedFile().getName();
                }
                System.out.println("Folder path: " + fileDir + " | File Name: " + chooser.getSelectedFile().getName());
                System.out.println(sourceFolder);
                if (e.getSource() == jButton1) {
                    checker3.setVisible(false);
                    f = chooser.getSelectedFile();
                    try {
                        fp = new FileProcessor(chooser.getSelectedFile(), 1);
                        ImageIcon i;
                        if (fp.CheckFile(1)) {
                            i = new ImageIcon(this.getClass().getResource("ch.png"));
                            contr[0] = true;
                        } else {
                            i = new ImageIcon(this.getClass().getResource("unch.png"));
                        }
                        checker1.setIcon(i);
                    } catch (IOException ex) {
                        //System.out.println("Loading first file fail! " + ex.getMessage());
                        eFrame = new ErrorFrame("<html><p>Načítanie prvého dokumentu zlyhalo!<br>" + ex.getMessage() + "</p></html>");
                    }
                }
                if (e.getSource() == jButton2) {
                    checker3.setVisible(false);
                    planF = chooser.getSelectedFile();
                    try {
                        fp = new FileProcessor(chooser.getSelectedFile(), 2);
                        ImageIcon i;
                        if (fp.CheckFile(2)) {
                            i = new ImageIcon(this.getClass().getResource("ch.png"));
                            contr[1] = true;
                        } else {
                            i = new ImageIcon(this.getClass().getResource("unch.png"));
                        }
                        contr[1] = true;
                        checker2.setIcon(i);
                    } catch (IOException ex) {
                        //System.out.println("Loading second file fail! " + ex.getMessage());
                        eFrame = new ErrorFrame("<html><p>Načítanie druhého dokumentu zlyhalo!<br>" + ex.getMessage() + "</p></html>");
                    }
                }
                /*if (contr[0] && contr[1]) {
                ImageIcon img = new ImageIcon(this.getClass().getResource("./img/RunBut2.png"));
                jButton5.setIcon(img);
            }*/
            }
            /*else {
            System.out.println("Nothing was selected!");
            OrdersField.setText("Súbor nebol zvolený");
        }*/
            //fileChecker();
        }
    }
/*
    public void paint(JPanel panel, Boolean b) throws IOException {
        BufferedImage img = getImg(b);
        panel.getGraphics().drawImage(img, 0, 0, panel);
    }

    public BufferedImage getImg(Boolean b) throws IOException {
        BufferedImage img;
        if (b) {
            img = ImageIO.read(new File("C:/Users/Anry/Documents/NetBeansProjects/Bakalarka/src/bakalarka/img_files/Checked.png"));
        } else {
            img = ImageIO.read(new File("C:/Users/Anry/Documents/NetBeansProjects/Bakalarka/src/bakalarka/img_files/unChecked.png"));
        }
        return img;
    }*/

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);

            }
        });
    }

    private EventHandler eventHandler;
    private int mouseX, mouseY;
    private String sourceFolder = "";
    private String theFile = "";
    private FileChooser chooser;
    private String chooserTitle;
    private File f = null;
    private File planF = null;
    private FileProcessor fp;
    //private GraphFrame frame;
    private File outputF = null;
    private String fileDir;
    private boolean[] contr = {false, false};
    private ErrorFrame eFrame;
    private HandleMouseEvt handlerMouse;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BoundsPanel;
    private javax.swing.JTextPane ContactTxt;
    private javax.swing.JPanel HeadPanel;
    private java.awt.Panel MainPanel;
    private javax.swing.JLabel OLabel1;
    private javax.swing.JTextPane OrdersPane;
    private javax.swing.JTextPane OrdersPane1;
    private javax.swing.JTextPane OrdersPane2;
    private javax.swing.JTextPane OrdersPane3;
    private javax.swing.JLabel checker1;
    private javax.swing.JLabel checker2;
    private javax.swing.JLabel checker3;
    private javax.swing.JLabel exitLabel;
    private javax.swing.JLabel exitLabel1;
    private javax.swing.JPanel horizontalLinePanel;
    private javax.swing.JPanel horizontalLinePanel1;
    private javax.swing.JPanel horizontalLinePanel2;
    private javax.swing.JTextField infoCheckNumField;
    private javax.swing.JTextField infoOperationNumField;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel logoLab;
    private javax.swing.JTextField missNumCheckField;
    private javax.swing.JTextArea misstakesArea;
    private java.awt.Panel panel1;
    private javax.swing.JPanel topPanel;
    private javax.swing.JPanel verticalLinePanel;
    // End of variables declaration//GEN-END:variables

    private class HandleMouseEvt implements MouseListener, MouseMotionListener {

        @Override
        public void mouseClicked(MouseEvent e) {
            if (e.getSource().equals(jButton3)) {
                if (!contr[0] || !contr[1]) {
                    Toolkit.getDefaultToolkit().beep();

                } else {
                    try {
                        DecimalFormat form = (DecimalFormat) DecimalFormat.getInstance();
                        form.applyPattern("#,###,##0");
                        fp = new FileProcessor(f, planF);
                        fp.WriteSortedProject(new File(fileDir + "/zotriedený_doc_NaV_"+ String.valueOf(fp.getYear()) +".xls"));
                        infoCheckNumField.setText(String.valueOf(form.format(fp.getNumOfRows())));
                        missNumCheckField.setText(String.valueOf(form.format(fp.getRowsOfPotentMiss())));
                        infoOperationNumField.setText(String.valueOf(form.format(fp.getOperationNum())));
                        misstakesArea.setText("");
                        List<String> strs = fp.getPotMissRows();
                        for (String str : strs) {
                            misstakesArea.append(str + "\n");
                        }
                        //fp.CheckIncomInPlan(new File(fileDir + "/checkedPlanTable.xls"));
                        Pair<Double, Double> p;
                        p = fp.WriteSalesByProject(planF);
                        JTableHeader th = jTable1.getTableHeader();
                        TableColumnModel tcm = th.getColumnModel();
                        TableColumn tc = tcm.getColumn(0);
                        tc.setHeaderValue("Za rok - " + String.valueOf(fp.getYear()));
                        th.repaint();
                        DecimalFormat formatter = (DecimalFormat) DecimalFormat.getInstance();
                        formatter.applyPattern("#,###,##0.00");
                        jTable1.setValueAt(formatter.format(p.getKey()), 0, 1);
                        jTable1.setValueAt(formatter.format(p.getValue()), 1, 1);
                        jTable1.setValueAt(formatter.format(p.getKey() - p.getValue()), 2, 1);
                        checker3.setVisible(true);
                    } catch (IOException ex) {
                        System.out.println("FileProcessor have problem! " + ex.getMessage());
                        eFrame = new ErrorFrame("<html><p>Spracovanie dát zlyhalo!<br><br>" + ex.getMessage() + "</p></html>");
                    }
                }
            }
            if (e.getSource().equals(jButton6)) {
                try {
                    AnalysisFrame aF = new AnalysisFrame();
                } catch (IOException ex) {
                    //System.out.println("Analysis startup error!");
                    eFrame = new ErrorFrame("<html><p>Finančná analýza dát zlyhala!<br><br>" + ex.getMessage() + "</p></html>");
                }
            }
            if (e.getSource().equals(jButton5)) {
                System.exit(0);
            }
        }

        @Override
        public void mousePressed(MouseEvent e) {
            if (e.getSource().equals(jButton1)) {
                ImageIcon img = new ImageIcon(this.getClass().getResource("Click1_clicked.png"));
                jButton1.setIcon(img);
            }
            if (e.getSource().equals(jButton2)) {
                ImageIcon img = new ImageIcon(this.getClass().getResource("Click2_clicked.png"));
                jButton2.setIcon(img);
            }
            if (e.getSource().equals(jButton3)) {
                ImageIcon img = new ImageIcon(this.getClass().getResource("Click3_clicked.png"));
                jButton3.setIcon(img);

            }
            if (e.getSource().equals(jButton6)) {
                ImageIcon img = new ImageIcon(this.getClass().getResource("RunBut1_clicked.png"));
                jButton6.setIcon(img);

            }
            if (e.getSource().equals(jButton5)) {
                ImageIcon img = new ImageIcon(this.getClass().getResource("Click4_clicked.png"));
                jButton5.setIcon(img);
            }
        }

        @Override
        public void mouseReleased(MouseEvent e) {
            if (e.getSource().equals(jButton1)) {
                ImageIcon img = new ImageIcon(this.getClass().getResource("Click1_def.png"));
                jButton1.setIcon(img);
            }
            if (e.getSource().equals(jButton2)) {
                ImageIcon img = new ImageIcon(this.getClass().getResource("Click2_def.png"));
                jButton2.setIcon(img);
            }
            if (e.getSource().equals(jButton3)) {
                ImageIcon img = new ImageIcon(this.getClass().getResource("Click3_hover.png"));
                jButton3.setIcon(img);

            }
            if (e.getSource().equals(jButton6)) {
                ImageIcon img = new ImageIcon(this.getClass().getResource("RunBut1_hover.png"));
                jButton6.setIcon(img);
            }
            if (e.getSource().equals(jButton5)) {
                ImageIcon img = new ImageIcon(this.getClass().getResource("Click4_hover.png"));
                jButton5.setIcon(img);
            }
        }

        @Override
        public void mouseEntered(MouseEvent e) {
            if (e.getSource().equals(jButton1)) {
                ImageIcon img = new ImageIcon(this.getClass().getResource("Click1_hover.png"));
                jButton1.setIcon(img);
                jButton1.setCursor(new Cursor(Cursor.HAND_CURSOR));
            }
            if (e.getSource().equals(jButton2)) {
                ImageIcon img = new ImageIcon(this.getClass().getResource("Click2_hover.png"));
                jButton2.setIcon(img);
                jButton2.setCursor(new Cursor(Cursor.HAND_CURSOR));
            }
            if (e.getSource().equals(jButton3)) {
                ImageIcon img = new ImageIcon(this.getClass().getResource("Click3_hover.png"));
                jButton3.setIcon(img);
                jButton3.setCursor(new Cursor(Cursor.HAND_CURSOR));
            }
            if (e.getSource().equals(jButton6)) {
                ImageIcon img = new ImageIcon(this.getClass().getResource("RunBut1_hover.png"));
                jButton6.setIcon(img);
                jButton6.setCursor(new Cursor(Cursor.HAND_CURSOR));
            }
            if (e.getSource().equals(jButton5)) {
                ImageIcon img = new ImageIcon(this.getClass().getResource("Click4_hover.png"));
                jButton5.setIcon(img);
                jButton5.setCursor(new Cursor(Cursor.HAND_CURSOR));
            }
        }

        @Override
        public void mouseExited(MouseEvent e) {
            if (e.getSource().equals(jButton1)) {
                ImageIcon img = new ImageIcon(this.getClass().getResource("Click1_def.png"));
                jButton1.setIcon(img);
                jButton1.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
            }
            if (e.getSource().equals(jButton2)) {
                ImageIcon img = new ImageIcon(this.getClass().getResource("Click2_def.png"));
                jButton2.setIcon(img);
                jButton2.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
            }
            if (e.getSource().equals(jButton3)) {
                ImageIcon img = new ImageIcon(this.getClass().getResource("Click3_def.png"));
                jButton3.setIcon(img);
                jButton3.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));

            }
            if (e.getSource().equals(jButton6)) {
                ImageIcon img = new ImageIcon(this.getClass().getResource("RunBut1.png"));
                jButton6.setIcon(img);
                jButton6.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));

            }
            if (e.getSource().equals(jButton5)) {
                ImageIcon img = new ImageIcon(this.getClass().getResource("Click4_def.png"));
                jButton5.setIcon(img);
                jButton5.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
            }
        }

        @Override
        public void mouseDragged(MouseEvent e) {
        }

        @Override
        public void mouseMoved(MouseEvent e) {
        }
    }
}
